/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouz.csb;

import javax.swing.JOptionPane;

/**
 *
 * @author oguzhan.turan
 */
public class loginPanel extends javax.swing.JPanel {

    /**
     * Creates new form loginPanel
     */
    public loginPanel() {
        initComponents();
    }

    public loginPanel(String kullaniciAdi, String sifre) {
        initComponents();

        txtKullaniciAdiPanel.setText(kullaniciAdi);
        txtSifrePanel.setText(sifre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKullaniciAdiPanel = new javax.swing.JTextField();
        btnKaydetPanel = new javax.swing.JButton();
        txtSifrePanel = new javax.swing.JPasswordField();

        jLabel1.setText("Kullanýcý Adý ");

        jLabel2.setText("Þifre");
        jLabel2.setToolTipText("");

        btnKaydetPanel.setText("Tamam");
        btnKaydetPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetPanelActionPerformed(evt);
            }
        });

        txtSifrePanel.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKaydetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKullaniciAdiPanel)
                    .addComponent(txtSifrePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKullaniciAdiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnKaydetPanel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetPanelActionPerformed

        String kAdi, pass;

        kAdi = txtKullaniciAdiPanel.getText();
        pass = txtSifrePanel.getPassword().toString();

        if (kAdi != null && pass != null) {
            mainFrame mF = new mainFrame(kAdi,pass);
            
            this.setVisible(false);
            this.setEnabled(false);
            mF.setEnabled(true);
            mF.setVisible(true);
        }
        else{
            if (kAdi == null ){
                JOptionPane.showMessageDialog(null,"Kullanýcý Adý alaný boþ geçilemez !\n", "HATA",JOptionPane.ERROR);
            }
            else{
                JOptionPane.showMessageDialog(null,"Þifre alaný boþ geçilemez !\n", "HATA",JOptionPane.ERROR);
            }
        }


    }//GEN-LAST:event_btnKaydetPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydetPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtKullaniciAdiPanel;
    private javax.swing.JPasswordField txtSifrePanel;
    // End of variables declaration//GEN-END:variables
}
